repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: isort-auto-commit
        name: Isort Auto Commit
        entry: bash -c 'isort "$@" && git add "$@"' --
        args: ["--sp", ".isort.cfg"]
        language: system
        types: [python]
        require_serial: true

      - id: black-auto-commit
        name: Black Auto Commit
        entry: bash -c 'black "$@" && git add "$@"' --
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config=.flake8]
